# -*- coding: utf-8 -*-
"""persona16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NMFs0vzqrBwus9WXBr4AeoxCLcqDrhZq
"""

# -*- coding: utf-8 -*-
"""persona11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RgJFo1Ny1M6MUVdQTQw6pckyAX_-pI02
"""
import os
import re
import json
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, GenerationConfig

# ===========================
# CONSTANTS AND SETTINGS
# ===========================

# Pairs of characters who will talk to each other
character_pairs = [
    ("Mother", "Daughter"), ("Daughter", "Mother"),
    ("Son", "Father"), ("Father", "Son"),
    ("Son", "Mother"), ("Mother", "Son"),
    ("Daughter", "Father"), ("Father", "Daughter")
]

# Prompt type variations with suffixes
prompt_types = {
    "Agreement": " There is agreement.",
    "Disagreement": " There is disagreement.",
    "Neutral": " There is no agreement or disagreement."
}

# Randomness settings for AI
temperatures = [0.1, 0.3, 0.5, 0.7, 0.9]

# Topics for conversation
topics = [
    "Education", "Curfew", "Homosexuality", "Singleness", "Cohabitation",
    "Religion", "Hijab", "Politics", "Interracial Marriage", "Pet Ownership"
]

# Country identity context
identities = {
    "Iran": "Iranian",
    "UK": "British"
}

model_list = [
    "google/gemma-3-1b-it",
    "google/gemma-3-4b-it",
    "deepseek-ai/deepseek-llm-7b-chat",
    "microsoft/Phi-3.5-mini-instruct",
    "meta-llama/Llama-3.2-3B-Instruct",
    "meta-llama/Llama-3.1-8B-Instruct",
    "microsoft/phi-4",
    "microsoft/Phi-3-medium-128k-instruct",
    "Qwen/Qwen2.5-1.5B-Instruct",
    "Qwen/Qwen2.5-7B-Instruct-1M",
    "Qwen/Qwen2.5-14B-Instruct-1M",
    "allenai/OLMo-2-1124-7B-Instruct",
    "allenai/OLMo-2-1124-13B-Instruct",
   
]

# Your HF API token
hf_token = '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'


# ===========================
# TEXT CLEANING FUNCTIONS
# ===========================
def clean_text(text):
    text = re.sub(r'\\u[0-9a-fA-F]{4}', '', text)
    text = re.sub(r'\n+', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    text = re.sub(r'[^\w\s.,!?\'"\[\]-]', '', text)
    text = text.replace('\"', '')
    text = re.sub(r'(\[.*?\])', r'\1: ', text)
    return text


def clean_to_full_sentence(text):
    matches = list(re.finditer(r'(?:\.\.\.|…|[.!?])', text))
    if matches:
        end = matches[-1].end()
        return text[:end].strip()
    return text.strip()


# ===========================
# MODEL LOADING FUNCTION
# ===========================
def load_model_tokenizer(model_name):
    """Load one model + tokenizer into GPU."""
    print(f"🔄 Loading model and tokenizer: {model_name}")
    tokenizer = AutoTokenizer.from_pretrained(model_name, token=hf_token, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        token=hf_token,
        device_map="auto",
        torch_dtype=torch.float16,
        trust_remote_code=True,
    )
    print(f"✅ Model loaded: {model_name}")
    return tokenizer, model


# ===========================
# PROMPT FORMATTING FUNCTION
# ===========================
def format_prompt(current_speaker, other_character, identity, topic, convo_history, prompt_suffix):
    system = (
        f"You are a {identity} {current_speaker.lower()} conversing with your "
        f"{identity} {other_character.lower()} about {topic.lower()}. "
        f"Speak in a tone and manner typical for that role and cultural context. "
        f"{prompt_suffix}\n"
    )
    chat = "\n".join(convo_history) if convo_history else ""
    prompt = system + chat + f"\n[{current_speaker.upper()}]:"
    print("\n--- Prompt Built ---")
    print(prompt)
    return prompt


# ===========================
# REPLY GENERATION FUNCTION
# ===========================
def generate_reply(tokenizer, model, prompt, temperature):
    print("\n--- Generating Reply ---")
    print(f"Temperature: {temperature}")
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    gen_cfg = GenerationConfig(
        temperature=temperature,
        top_p=0.9,
        do_sample=True,
        max_new_tokens=30
    )
    outputs = model.generate(**inputs, generation_config=gen_cfg, pad_token_id=tokenizer.eos_token_id)
    text = tokenizer.decode(outputs[0], skip_special_tokens=True)

    raw_reply = text.split(f"{prompt.splitlines()[-1]}")[-1].strip()
    print(f"\n[RAW REPLY]: {raw_reply}")

    cleaned_reply = clean_text(raw_reply)
    final_reply = clean_to_full_sentence(cleaned_reply)

    print(f"[CLEANED REPLY]: {cleaned_reply}")
    print(f"[FINAL REPLY]: {final_reply}")

    return final_reply


# ===========================
# MAIN CONVERSATION GENERATOR
# ===========================
def generate_conversation(
    tokenizer_a, model_a,
    tokenizer_b, model_b,
    first_character,
    second_character,
    prompt_type,
    prompt_suffix,
    temperature,
    topic,
    identity_label,
    file_num
):
    print(f"\n🟢 START: {identity_label} | {first_character}-{second_character} "
          f"[{prompt_type}] | Topic: {topic} | Temp: {temperature}")

    try:
        identity = identities[identity_label]

        conversation_history = []
        conversation_data = {"dialog": []}

        starter = f"{first_character}: Let's talk about {topic.lower()}. What are your thoughts?"
        conversation_history.append(starter)
        print(f"\n[STARTER]: {starter}")

        for i in range(10):
            print(f"\n================= ROUND {i+1} =================")
            for current_speaker, other_character, tokenizer, model in [
                (second_character, first_character, tokenizer_b, model_b),
                (first_character, second_character, tokenizer_a, model_a)
            ]:
                print(f"\n--- {current_speaker} is speaking to {other_character} ---")
                print(f"[CONVERSATION HISTORY]: {conversation_history}")

                prompt = format_prompt(
                    current_speaker=current_speaker,
                    other_character=other_character,
                    identity=identity,
                    topic=topic,
                    convo_history=conversation_history,
                    prompt_suffix=prompt_suffix
                )

                reply = generate_reply(tokenizer, model, prompt, temperature)

                conversation_history.append(f"{current_speaker}: {reply}")
                conversation_data["dialog"].append({current_speaker: reply})
                print(f"[ADDED TO HISTORY]: {current_speaker}: {reply}")

        base_save_path = "/home/shekhar/Desktop/code/persona/output2"
        model_folder = model_a.name_or_path.replace("/", "_")
        if identity_label == "UK":
            model_folder = f"{model_folder}_UK"
        elif identity_label == "Iran":
            model_folder = f"{model_folder}_IR"

        save_dir = os.path.join(
            base_save_path,
            "Dissertation_All_Models",
            model_folder,
            topic
        )
        os.makedirs(save_dir, exist_ok=True)

        filename = f"{topic}_temp_{temperature}_{file_num}_{first_character}_{second_character}_{prompt_type}.json"
        filepath = os.path.join(save_dir, filename)

        with open(filepath, "w") as f:
            json.dump(conversation_data, f, indent=4)

        print(f"✅ Saved: {filepath}")

    except Exception as e:
        print(f"❌ ERROR: {e}")


# ===========================
# MAIN EXECUTION LOOP
# ===========================
for model_name in model_list:
    print(f"\n======================")
    print(f"🚀 Processing model: {model_name}")
    print(f"======================")

    # Load ONE model into GPU at a time
    tokenizer_a, model_a = load_model_tokenizer(model_name)
    tokenizer_b, model_b = tokenizer_a, model_a  # Both speakers use the same model

    for identity in identities.keys():
        for topic in topics:
            for first_character, second_character in character_pairs:
                for prompt_type, suffix in prompt_types.items():
                    for temp in temperatures:
                        for file_num in range(1, 6):
                            generate_conversation(
                                tokenizer_a=tokenizer_a,
                                model_a=model_a,
                                tokenizer_b=tokenizer_b,
                                model_b=model_b,
                                first_character=first_character,
                                second_character=second_character,
                                prompt_type=prompt_type,
                                prompt_suffix=suffix,
                                temperature=temp,
                                topic=topic,
                                identity_label=identity,
                                file_num=file_num
                            )

    # ✅ Free GPU memory after finishing this model
    print(f"\n🧹 Clearing GPU memory for model: {model_name}")
    del model_a, model_b, tokenizer_a, tokenizer_b
    torch.cuda.empty_cache()
